#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""One-off generator for s1_en/ko/ja.py — run then delete if desired."""

from pathlib import Path

ENTRIES = []  # populated below


def write_file(path: Path, lang: str, pairs):
    pairs = sorted(pairs, key=lambda x: len(x[0]), reverse=True)
    out = [
        "# -*- coding: utf-8 -*-",
        f'"""S1 zh → {lang} replacements for fomo-season-1.html."""',
        "",
        "REPLACEMENTS = [",
    ]
    for zh, tr in pairs:
        def esc(s: str) -> str:
            return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        zh_esc, tr_esc = esc(zh), esc(tr)
        out.append(f'    ("{zh_esc}", "{tr_esc}"),')
    out.append("]")
    out.append("")
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"{path}: {len(pairs)} tuples")


# fmt: off
ENTRIES = [
    ('<html lang="zh">', '<html lang="en">', '<html lang="ko">', '<html lang="ja">'),
    ('<meta property="og:locale" content="zh_CN">', '<meta property="og:locale" content="en_US">', '<meta property="og:locale" content="ko_KR">', '<meta property="og:locale" content="ja_JP">'),
    ('<title>FOMO Reward Season 1 · 真实使用驱动的奖励</title>', '<title>FOMO Reward Season 1 · Real usage-driven rewards</title>', '<title>FOMO Reward Season 1 · 실사용 기반 보상</title>', '<title>FOMO Reward Season 1 · 実利用に基づく報酬</title>'),
    ('<meta name="description" content="FOMO Reward Season 1：真实 API 使用驱动奖励。支出即引擎、MT 双池激励、gmFLOCK 全局乘子与 usage-backed rewards。">', '<meta name="description" content="FOMO Reward Season 1: usage-backed rewards driven by real API calls. Spend as the engine, dual MT pools, gmFLOCK global multiplier, and usage-backed rewards.">', '<meta name="description" content="FOMO Reward Season 1: 실제 API 사용량 기반 보상. 지출이 엔진, MT 듀얼 풀, gmFLOCK 글로벌 배수, usage-backed rewards.">', '<meta name="description" content="FOMO Reward Season 1：実際のAPI使用量に基づく報酬。支出がエンジン、MTデュアルプール、gmFLOCKグローバル乗数、usage-backed rewards。">'),
    ('<meta property="og:title" content="FOMO Reward Season 1 · 真实使用驱动的奖励">', '<meta property="og:title" content="FOMO Reward Season 1 · Real usage-driven rewards">', '<meta property="og:title" content="FOMO Reward Season 1 · 실사용 기반 보상">', '<meta property="og:title" content="FOMO Reward Season 1 · 実利用に基づく報酬">'),
    ('<meta property="og:description" content="真实 API 使用驱动奖励。支出即引擎、Model Token 双池、gmFLOCK 全局乘子与 usage-backed rewards。">', '<meta property="og:description" content="Usage-backed rewards driven by real API calls. Spend as the engine, Model Token dual pools, gmFLOCK global multiplier, and usage-backed rewards.">', '<meta property="og:description" content="실제 API 사용량 기반 보상. 지출이 엔진, Model Token 듀얼 풀, gmFLOCK 글로벌 배수, usage-backed rewards.">', '<meta property="og:description" content="実際のAPI使用量に基づく報酬。支出がエンジン、Model Tokenデュアルプール、gmFLOCKグローバル乗数、usage-backed rewards。">'),
    ('<meta property="og:image:alt" content="FOMO Reward Season 1 — 真实使用驱动的奖励">', '<meta property="og:image:alt" content="FOMO Reward Season 1 — Real usage-driven rewards">', '<meta property="og:image:alt" content="FOMO Reward Season 1 — 실사용 기반 보상">', '<meta property="og:image:alt" content="FOMO Reward Season 1 — 実利用に基づく報酬">'),
    ('<meta name="twitter:title" content="FOMO Reward Season 1 · 真实使用驱动的奖励">', '<meta name="twitter:title" content="FOMO Reward Season 1 · Real usage-driven rewards">', '<meta name="twitter:title" content="FOMO Reward Season 1 · 실사용 기반 보상">', '<meta name="twitter:title" content="FOMO Reward Season 1 · 実利用に基づく報酬">'),
    ('<meta name="twitter:description" content="真实 API 使用驱动奖励、MT 双池、gmFLOCK 全局乘子。">', '<meta name="twitter:description" content="Real API usage drives rewards — dual MT pools, gmFLOCK global multiplier.">', '<meta name="twitter:description" content="실제 API 사용량 기반 보상, MT 듀얼 풀, gmFLOCK 글로벌 배수.">', '<meta name="twitter:description" content="実際のAPI使用量に基づく報酬、MTデュアルプール、gmFLOCKグローバル乗数。">'),
    ('href="fomo-newbie-guide_May"', 'href="fomo-newbie-guide_May-en.html"', 'href="fomo-newbie-guide_May-ko.html"', 'href="fomo-newbie-guide_May-ja.html"'),
    ('fomo-season-2.html', 'fomo-season-2-en.html', 'fomo-season-2-ko.html', 'fomo-season-2-ja.html'),
    ('aria-label="返回 FOMO 新手手册"', 'aria-label="Back to the FOMO guide"', 'aria-label="FOMO 가이드로 돌아가기"', 'aria-label="FOMO ガイドへ戻る"'),
    ('<span class="hbar-dd-sub">真实使用 → 奖励飞轮</span>', '<span class="hbar-dd-sub">Real usage → reward flywheel</span>', '<span class="hbar-dd-sub">실사용 → 보상 플라이휠</span>', '<span class="hbar-dd-sub">実利用 → 報酬フライホイール</span>'),
    ('<span class="hbar-dd-sub">敬请期待 · TBA</span>', '<span class="hbar-dd-sub">Coming soon · TBA</span>', '<span class="hbar-dd-sub">곧 공개 · TBA</span>', '<span class="hbar-dd-sub">近日公開 · TBA</span>'),
    (' aria-label="前往产品平台">', '>', '>', '>'),
    ('<span class="lbl-full">FOMO 平台</span>', '<span class="lbl-full">FOMO App</span>', '<span class="lbl-full">FOMO 앱</span>', '<span class="lbl-full">FOMO アプリ</span>'),
    ('<i data-lucide="arrow-left"></i> 返回新手手册', '<i data-lucide="arrow-left"></i> Back to guide', '<i data-lucide="arrow-left"></i> 가이드로 돌아가기', '<i data-lucide="arrow-left"></i> ガイドへ戻る'),
    ('FOMO Reward Season 1 · <span class="accent">真实使用驱动的奖励</span>', 'FOMO Reward Season 1 · <span class="accent">Real usage-driven rewards</span>', 'FOMO Reward Season 1 · <span class="accent">실사용 기반 보상</span>', 'FOMO Reward Season 1 · <span class="accent">実利用に基づく報酬</span>'),
    ('一句话原则：<b style="color:#fff;font-weight:500">用了 AI 就有奖励</b>。\n      通过 FLock 平台调用 AI 模型（每个模型对应一个 Model Token，简称 <b style="color:#fff;font-weight:500">MT</b>），你的 API 使用量会自动转化为每日 <b style="color:#fff;font-weight:500">FLOCK</b> 代币奖励。\n      质押你在用的 MT 可以加倍，持有 <b style="color:#fff;font-weight:500">gmFLOCK</b> 还能全局加成。', 'One-line principle: <b style="color:#fff;font-weight:500">use AI, earn rewards</b>.\n      Call AI models on the FLock platform (each model maps to a Model Token, or <b style="color:#fff;font-weight:500">MT</b>); your API usage automatically converts into daily <b style="color:#fff;font-weight:500">FLOCK</b> token rewards.\n      Stake the MT you actually use to multiply your share; holding <b style="color:#fff;font-weight:500">gmFLOCK</b> adds a global boost.', '한 줄 원칙: <b style="color:#fff;font-weight:500">AI를 쓰면 보상이 있습니다</b>.\n      FLock 플랫폼에서 AI 모델을 호출하면(각 모델은 Model Token, <b style="color:#fff;font-weight:500">MT</b>에 해당) API 사용량이 매일 <b style="color:#fff;font-weight:500">FLOCK</b> 토큰 보상으로 자동 전환됩니다.\n      사용 중인 MT를 스테이킹하면 배수가 올라가고, <b style="color:#fff;font-weight:500">gmFLOCK</b>을 보유하면 글로벌 부스트가 추가됩니다.', '一言で言うと：<b style="color:#fff;font-weight:500">AIを使えば報酬がある</b>。\n      FLockプラットフォームでAIモデルを呼び出すと（各モデルはModel Token、<b style="color:#fff;font-weight:500">MT</b>に対応）、API使用量は毎日<b style="color:#fff;font-weight:500">FLOCK</b>トークン報酬に自動変換されます。\n      使用中のMTをステーキングすると倍率が上がり、<b style="color:#fff;font-weight:500">gmFLOCK</b>を保有するとグローバルブーストが加わります。'),
    ('<div class="chip"><b>花钱调 API</b> → 每天发奖励</div>', '<div class="chip"><b>Spend on API</b> → daily rewards</div>', '<div class="chip"><b>API 비용 지출</b> → 매일 보상</div>', '<div class="chip"><b>API費用を使う</b> → 毎日報酬</div>'),
    ('<div class="chip">每 MT 双池 · <b>FLOCK + 原生币</b></div>', '<div class="chip">Dual pool per MT · <b>FLOCK + native token</b></div>', '<div class="chip">MT당 듀얼 풀 · <b>FLOCK + 네이티브 토큰</b></div>', '<div class="chip">MTごとにデュアルプール · <b>FLOCK + ネイティブトークン</b></div>'),
    ('<div class="chip">~<b>180 天</b> 线性释放</div>', '<div class="chip">~<b>180 days</b> linear emission</div>', '<div class="chip">~<b>180일</b> 선형 방출</div>', '<div class="chip">~<b>180日</b> リニアエミッション</div>'),
    ('<div class="chip"><b>gmFLOCK</b> 全局加成</div>', '<div class="chip"><b>gmFLOCK</b> global boost</div>', '<div class="chip"><b>gmFLOCK</b> 글로벌 부스트</div>', '<div class="chip"><b>gmFLOCK</b> グローバルブースト</div>'),
    ('<div class="chip">早入场更友好，后期<b>质押优势</b>更大</div>', '<div class="chip">Early entry is easier; later, <b>staking edge</b> grows</div>', '<div class="chip">일찍 참여할수록 유리, 후반엔 <b>스테이킹 우위</b>가 커짐</div>', '<div class="chip">早く入るほど有利、後半は<b>ステーキング優位</b>が拡大</div>'),
    ('<h3 data-anim style="font-size:22px;margin-bottom:18px;">本季三件事</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">Three things this season</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">이번 시즌 세 가지</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">今シーズンの3つのポイント</h3>'),
    ('<h3>用得多，分得多</h3>', '<h3>More usage, bigger share</h3>', '<h3>많이 쓸수록, 더 많이</h3>', '<h3>使えば使うほど、多く分配</h3>'),
    ('你在某个 MT 上的奖励份额，与你在该 MT 的 API 花费占比<b style="color:#fff;font-weight:500">成正比</b> —— 用得越多，当日分到的 FLOCK 越多。奖励的是真实 AI 调用，不是刷量套利。', "Your reward share on a given MT is <b style=\"color:#fff;font-weight:500\">proportional</b> to your share of that MT's API spend — the more you use, the more FLOCK you earn that day. Rewards go to real AI calls, not wash trading.", '특정 MT에서의 보상 몫은 해당 MT API 지출 비중과 <b style="color:#fff;font-weight:500">비례</b>합니다 — 많이 쓸수록 그날 더 많은 FLOCK을 받습니다. 보상은 실제 AI 호출에만 주어지며, 거래량 조작이 아닙니다.', 'あるMTでの報酬シェアは、そのMTのAPI支出シェアに<b style="color:#fff;font-weight:500">比例</b>します — 使えば使うほど、その日のFLOCKが増えます。報酬は実際のAI呼び出しに対してであり、出来高操作ではありません。'),
    ('举例：你在 Model A 花了 100 USDC，全池共 1000 USDC，你大约能拿到该池 <b style="color:#fff;font-weight:500">10%</b> 的当日 FLOCK 奖励（未计质押 / gmFLOCK 加成）。', "Example: you spend 100 USDC on Model A while the full pool totals 1000 USDC — you'd get about <b style=\"color:#fff;font-weight:500\">10%</b> of that day's FLOCK rewards from that pool (before staking / gmFLOCK boosts).", '예: Model A에 100 USDC를 쓰고 전체 풀이 1000 USDC라면, 해당 풀 당일 FLOCK 보상의 약 <b style="color:#fff;font-weight:500">10%</b>를 받을 수 있습니다(스테이킹 / gmFLOCK 부스트 제외).', '例：Model Aに100 USDCを使い、プール合計が1000 USDCなら、そのプールの当日FLOCK報酬の約<b style="color:#fff;font-weight:500">10%</b>を受け取れます（ステーキング / gmFLOCKブースト除く）。'),
    ('<h3>每个模型，双份奖励</h3>', '<h3>Every model, two reward streams</h3>', '<h3>모델마다, 두 가지 보상</h3>', '<h3>モデルごとに、二重の報酬</h3>'),
    ('每个支持的 MT 都有<b style="color:#fff;font-weight:500">两份激励</b>：一份 FLOCK，一份该模型自己的代币，约 <b style="color:#fff;font-weight:500">180 天</b>慢慢发完。参与多个模型，奖励<b style="color:#fff;font-weight:500">各自累加</b>，不会互相抢份额。', "Every supported MT has <b style=\"color:#fff;font-weight:500\">two incentives</b>: FLOCK plus that model's native token, emitted over about <b style=\"color:#fff;font-weight:500\">180 days</b>. Join multiple models and rewards <b style=\"color:#fff;font-weight:500\">stack separately</b> — pools don't compete for the same share.", '지원되는 MT마다 <b style="color:#fff;font-weight:500">두 가지 인센티브</b>가 있습니다: FLOCK과 해당 모델 토큰, 약 <b style="color:#fff;font-weight:500">180일</b>에 걸쳐 방출됩니다. 여러 모델에 참여하면 보상은 <b style="color:#fff;font-weight:500">각각 누적</b>되며, 서로 몫을 빼앗지 않습니다.', 'サポートされるMTごとに<b style="color:#fff;font-weight:500">二つのインセンティブ</b>があります：FLOCKとそのモデルトークン、約<b style="color:#fff;font-weight:500">180日</b>かけて放出されます。複数モデルに参加すると報酬は<b style="color:#fff;font-weight:500">それぞれ加算</b>され、シェアを奪い合いません。'),
    ('举例：你同时用 Model A 和 Model B，两个池子的 FLOCK 奖励会<b style="color:#fff;font-weight:500">分别计算、分别领取</b>。', 'Example: if you use Model A and Model B, FLOCK rewards from both pools are <b style="color:#fff;font-weight:500">calculated and claimed separately</b>.', '예: Model A와 Model B를 동시에 쓰면, 두 풀의 FLOCK 보상은 <b style="color:#fff;font-weight:500">각각 계산·수령</b>됩니다.', '例：Model AとModel Bを同時に使うと、両プールのFLOCK報酬は<b style="color:#fff;font-weight:500">別々に計算・受け取り</b>できます。'),
    ('<h3>质押 + gmFLOCK = 双重加速</h3>', '<h3>Stake + gmFLOCK = double boost</h3>', '<h3>스테이킹 + gmFLOCK = 이중 가속</h3>', '<h3>ステーキング + gmFLOCK = 二重ブースト</h3>'),
    ('同样花 100 USDC 调 API，<b style="color:#fff;font-weight:500">质押了对应 MT</b> 会比不质押拿得更多。<b style="color:#fff;font-weight:500">gmFLOCK</b> 像「全场 VIP 卡」—— 持有后，你在每个 MT 上的得分都会一起放大，小户也能感受到差别。', 'Spending the same 100 USDC on API calls, <b style="color:#fff;font-weight:500">staking the matching MT</b> earns more than not staking. <b style="color:#fff;font-weight:500">gmFLOCK</b> works like an all-access VIP pass — hold it and your score on every MT gets boosted, so smaller holders still feel the difference.', '같은 100 USDC로 API를 호출해도, <b style="color:#fff;font-weight:500">해당 MT를 스테이킹</b>하면 스테이킹하지 않을 때보다 더 많이 받습니다. <b style="color:#fff;font-weight:500">gmFLOCK</b>은 「전장 VIP 카드」처럼 — 보유하면 참여하는 모든 MT 점수가 함께 올라가 소액 참여자도 차이를 느낄 수 있습니다.', '同じ100 USDCでAPIを呼び出しても、<b style="color:#fff;font-weight:500">対応するMTをステーキング</b>すると未ステーキングより多く受け取れます。<b style="color:#fff;font-weight:500">gmFLOCK</b>は「全场VIPカード」のように — 保有すると参加するすべてのMTのスコアがまとめて上がり、小口保有者も差を実感できます。'),
    ('举例：不质押时占比 10%；质押后可能提升到约 15%；再持有 gmFLOCK，可能再抬到约 18%（示意，非链上精确值）。', 'Example: 10% share without staking; staking might lift it to ~15%; add gmFLOCK and it could reach ~18% (illustrative, not exact on-chain values).', '예: 스테이킹 없이 10%; 스테이킹 후 약 15%; gmFLOCK까지 보유하면 약 18%까지 올라갈 수 있습니다(시뮬, 온체인 정확값 아님).', '例：ステーキングなし10%；ステーキング後は約15%；gmFLOCK保有で約18%まで上がる可能性（デモ、オンチェーンの正確値ではありません）。'),
    ('<div class="calc-head">试一试 · 奖励份额示意（非精确链上数据）</div>', '<div class="calc-head">Try it · reward share preview (not exact on-chain data)</div>', '<div class="calc-head">체험하기 · 보상 몫 미리보기(온체인 정확 데이터 아님)</div>', '<div class="calc-head">試してみる · 報酬シェアのデモ（オンチェーンの正確データではありません）</div>'),
    ('<label for="s1MySpend">你的 API 花费 (USDC)</label>', '<label for="s1MySpend">Your API spend (USDC)</label>', '<label for="s1MySpend">내 API 지출 (USDC)</label>', '<label for="s1MySpend">あなたのAPI支出 (USDC)</label>'),
    ('<label for="s1PoolSpend">该 MT 全池总花费 (USDC)</label>', '<label for="s1PoolSpend">Total pool spend for this MT (USDC)</label>', '<label for="s1PoolSpend">해당 MT 풀 총 지출 (USDC)</label>', '<label for="s1PoolSpend">このMTプールの総支出 (USDC)</label>'),
    ('<label>是否质押你在用的 MT</label>', '<label>Stake the MT you use?</label>', '<label>사용 중인 MT를 스테이킹했나요?</label>', '<label>使用中のMTをステーキングしていますか？</label>'),
    ('<button type="button" data-stake="0">不质押</button>', '<button type="button" data-stake="0">Not staked</button>', '<button type="button" data-stake="0">미스테이킹</button>', '<button type="button" data-stake="0">未ステーキング</button>'),
    ('<button type="button" data-stake="1" class="on">已质押</button>', '<button type="button" data-stake="1" class="on">Staked</button>', '<button type="button" data-stake="1" class="on">스테이킹함</button>', '<button type="button" data-stake="1" class="on">ステーキング済み</button>'),
    ('<label for="s1Gm">gmFLOCK 持有量（示意）</label>', '<label for="s1Gm">gmFLOCK holdings (illustrative)</label>', '<label for="s1Gm">gmFLOCK 보유량(시뮬)</label>', '<label for="s1Gm">gmFLOCK保有量（デモ）</label>'),
    ('<div style="font-size:12px;color:var(--txt-3);font-family:var(--mono);">你的预估日奖励占比（示意）</div>', '<div style="font-size:12px;color:var(--txt-3);font-family:var(--mono);">Your estimated daily reward share (illustrative)</div>', '<div style="font-size:12px;color:var(--txt-3);font-family:var(--mono);">예상 일일 보상 비중(시뮬)</div>', '<div style="font-size:12px;color:var(--txt-3);font-family:var(--mono);">推定の日次報酬シェア（デモ）</div>'),
    ('<p class="sub" id="s1ShareExplain">基础份额 10%（100÷1000）× 质押加成 × gmFLOCK 加成 ≈ 15.0%</p>', '<p class="sub" id="s1ShareExplain">Base share 10% (100÷1000) × staking boost × gmFLOCK boost ≈ 15.0%</p>', '<p class="sub" id="s1ShareExplain">기본 몫 10% (100÷1000) × 스테이킹 부스트 × gmFLOCK 부스트 ≈ 15.0%</p>', '<p class="sub" id="s1ShareExplain">基本シェア10% (100÷1000) × ステーキングブースト × gmFLOCKブースト ≈ 15.0%</p>'),
    ('<p class="calc-note">说明：真实链上还会考虑多人竞争、池子规则等；此处仅帮助理解「花得多 + 质押 + gmFLOCK」如何抬高你的份额。</p>', '<p class="calc-note">Note: on-chain math also factors in competition and pool rules; this preview shows how spend + staking + gmFLOCK lift your share.</p>', '<p class="calc-note">참고: 실제 온체인에서는 경쟁, 풀 규칙 등이 반영됩니다. 여기서는 「많이 쓰기 + 스테이킹 + gmFLOCK」이 몫을 어떻게 올리는지 이해하는 용도입니다.</p>', '<p class="calc-note">注：オンチェーンでは競合やプールルールも考慮されます。ここでは「使う + ステーキング + gmFLOCK」がシェアをどう押し上げるかを理解するためのものです。</p>'),
    ('<div class="val" id="s1GmVal">中等持有</div>', '<div class="val" id="s1GmVal">Moderate holdings</div>', '<div class="val" id="s1GmVal">중간 보유</div>', '<div class="val" id="s1GmVal">中程度の保有</div>'),
    ('<h3 data-anim style="font-size:22px;margin-bottom:18px;">为什么这对 FLOCK 是长期利好</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">Why this is good for FLOCK long term</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">FLOCK에 장기적으로 왜 좋은가</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">FLOCKにとって長期的に良い理由</h3>'),
    ('<h3>奖励只给真正用 AI 的人</h3>', '<h3>Rewards go to people who actually use AI</h3>', '<h3>보상은 AI를 실제로 쓰는 사람에게</h3>', '<h3>報酬はAIを本当に使う人へ</h3>'),
    ('每天发出的 FLOCK，主要流向<b style="color:#fff;font-weight:500">真的在被调用</b>的模型。光质押不调用，很难分到多少；为了刷量而乱调 API，花费往往比回报还高。', "Daily FLOCK emissions flow mainly to models that are <b style=\"color:#fff;font-weight:500\">actually being called</b>. Stake without usage and you won't earn much; spam API calls to farm rewards and spend often exceeds payout.", '매일 방출되는 FLOCK은 주로 <b style="color:#fff;font-weight:500">실제로 호출되는</b> 모델로 흐릅니다. 스테이킹만 하고 호출하지 않으면 거의 못 받고, 보상을 위해 API를 남용하면 비용이 수익을 넘기기 쉽습니다.', '毎日放出されるFLOCKは主に<b style="color:#fff;font-weight:500">実際に呼び出されている</b>モデルへ流れます。ステーキングだけではほとんど得られず、報酬目的のAPI乱用はコストがリターンを上回りがちです。'),
    ('<h3>越早参与，成本越低</h3>', '<h3>Earlier entry, lower cost</h3>', '<h3>일찍 참여할수록 비용이 낮음</h3>', '<h3>早く参加するほどコストが低い</h3>'),
    ('随着更多 Agent 和第三方模型接入，每个池子里想拿到「可观份额」需要的花费会逐渐变多。也就是说，流出的 FLOCK 背后多是<b style="color:#fff;font-weight:500">真实经济活动</b>，不是无脑空投。', 'As more agents and third-party models join, earning a meaningful share in each pool takes more spend. FLOCK flowing out backs <b style="color:#fff;font-weight:500">real economic activity</b>, not blind airdrops.', '더 많은 Agent와 서드파티 모델이 붙을수록, 각 풀에서 「의미 있는 몫」을 얻기 위한 지출은 점점 늘어납니다. 즉 유출되는 FLOCK 뒤에는 <b style="color:#fff;font-weight:500">실제 경제 활동</b>이 있고, 무작위 에어드rop이 아닙니다.', 'Agentやサードパーティモデルが増えるほど、各プールで「目に見えるシェア」を得るための支出は増えます。つまり流出するFLOCKの裏には<b style="color:#fff;font-weight:500">実際の経済活動</b>があり、盲目的なエアドropではありません。'),
    ('<h3>模型越多，奖池越大</h3>', '<h3>More models, bigger reward pools</h3>', '<h3>모델이 많을수록, 보상 풀이 커짐</h3>', '<h3>モデルが増えるほど、報酬プールが拡大</h3>'),
    ('每多一个 MT，就多一个激励池，吸引更多开发者和用户把 API 花费<b style="color:#fff;font-weight:500">汇进 FLOCK 奖励循环</b>。', 'Each new MT adds another incentive pool, pulling more developers and users to route API spend <b style="color:#fff;font-weight:500">into the FLOCK reward loop</b>.', 'MT가 하나 늘 때마다 인센티브 풀이 추가되어, 더 많은 개발자와 사용자가 API 지출을 <b style="color:#fff;font-weight:500">FLOCK 보상 루프</b>로 모으게 됩니다.', 'MTが増えるたびにインセンティブプールが増え、より多くの開発者とユーザーがAPI支出を<b style="color:#fff;font-weight:500">FLOCK報酬ループ</b>へ集めます。'),
    ('<h3>一份 gmFLOCK，所有模型都加成</h3>', '<h3>One gmFLOCK, boost on every model</h3>', '<h3>gmFLOCK 하나로, 모든 모델에 부스트</h3>', '<h3>gmFLOCK一枚で、全モデルにブースト</h3>'),
    ('持有一份 gmFLOCK，就能在<b style="color:#fff;font-weight:500">所有</b>你参与的 MT 上同时享受加成；平台模型越多，这张「全场卡」覆盖的面越广。', 'Hold one gmFLOCK and get a boost on <b style="color:#fff;font-weight:500">every</b> MT you join; as the platform adds models, this all-access pass covers more ground.', 'gmFLOCK을 하나 보유하면 참여하는 <b style="color:#fff;font-weight:500">모든</b> MT에서 동시에 부스트를 받습니다. 플랫폼 모델이 늘수록 이 「전장 패스」의 범위가 넓어집니다.', 'gmFLOCKを1枚保有すれば、参加する<b style="color:#fff;font-weight:500">すべての</b>MTで同時にブーストを受けられます。プラットフォームのモデルが増えるほど、この「全场パス」のカバー範囲が広がります。'),
    ('<p class="av-head"><b>早期入场优势：</b>现阶段只需少量质押就能获得不错的加成。随着 Season 推进，质押相对不质押的优势会逐步拉大 —— 简单说：<b>越早质押，同样花费下拿到的奖励越多。</b></p>', '<p class="av-head"><b>Early-entry edge:</b> right now a modest stake already buys a solid boost. As the Season progresses, staking vs not staking pulls further apart — <b>stake earlier and the same spend earns more.</b></p>', '<p class="av-head"><b>얼리 참여 우위:</b> 지금은 적은 스테이킹으로도 괜찮은 부스트를 받을 수 있습니다. Season이 진행될수록 스테이킹 vs 미스테이킹 격차는 커집니다 — <b>일찍 스테이킹할수록 같은 지출로 더 많은 보상.</b></p>', '<p class="av-head"><b>早期参加の優位：</b>現段階では少額のステーキングでも十分なブーストが得られます。Seasonが進むほど、ステーキング有無の差は広がります — <b>早くステーキングするほど、同じ支出でより多くの報酬。</b></p>'),
    ('<label><span>Season 早期</span><span id="avPhaseLabel">进行中 · 约 40%</span><span>Season 后期</span></label>', '<label><span>Early Season</span><span id="avPhaseLabel">Mid-season · ~40%</span><span>Late Season</span></label>', '<label><span>Season 초반</span><span id="avPhaseLabel">진행 중 · 약 40%</span><span>Season 후반</span></label>', '<label><span>Season序盤</span><span id="avPhaseLabel">進行中 · 約40%</span><span>Season終盤</span></label>'),
    ('aria-label="Season 时间进度"', 'aria-label="Season timeline progress"', 'aria-label="Season 시간 진행"', 'aria-label="Seasonタイムライン進行"'),
    ('<div class="k">不质押 · 相对得分（示意）</div>', '<div class="k">Not staked · relative score (illustrative)</div>', '<div class="k">미스테이킹 · 상대 점수(시뮬)</div>', '<div class="k">未ステーキング · 相対スコア（デモ）</div>'),
    ('<div class="k">质押 · 相对得分（示意）</div>', '<div class="k">Staked · relative score (illustrative)</div>', '<div class="k">스테이킹 · 상대 점수(시뮬)</div>', '<div class="k">ステーキング · 相対スコア（デモ）</div>'),
    ('<p class="av-gap" id="avGapText">当前阶段：质押比不质押大约多 <b style="color:#fff">36%</b> 得分（α≈0.74，仅作理解用）。</p>', '<p class="av-gap" id="avGapText">At this stage: staking earns about <b style="color:#fff">36%</b> more score than not staking (α≈0.74, illustrative only).</p>', '<p class="av-gap" id="avGapText">현재 단계: 스테이킹이 미스테이킹보다 약 <b style="color:#fff">36%</b> 더 많은 점수(α≈0.74, 이해용).</p>', '<p class="av-gap" id="avGapText">現段階：ステーキングは未ステーキングより約<b style="color:#fff">36%</b>多いスコア（α≈0.74、理解用）。</p>'),
    ('<h3 data-anim style="font-size:22px;margin-bottom:18px;">把 AI 使用直接接入链上飞轮</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">Plug AI usage straight into the on-chain flywheel</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">AI 사용을 온체인 플라이휠에 직접 연결</h3>', '<h3 data-anim style="font-size:22px;margin-bottom:18px;">AI利用をオンチェーンフライホイールに直結</h3>'),
    ('Season 1 不只是「多发一点币」，而是让<b style="color:#fff;font-weight:500">真实 AI 使用</b>变成链上激励的起点：\n      你调 API 的钱，同时也在参与 FLOCK 经济循环。', 'Season 1 isn\'t just "more tokens" — it makes <b style="color:#fff;font-weight:500">real AI usage</b> the starting point for on-chain incentives:\n      the money you spend on API calls also feeds the FLOCK economic loop.', 'Season 1은 단순히 「코인을 더 주는 것」이 아니라, <b style="color:#fff;font-weight:500">실제 AI 사용</b>을 온체인 인센티브의 시작점으로 만듭니다:\n      API에 쓰는 돈이 동시에 FLOCK 경제 루프에 참여합니다.', 'Season 1は「トークンを多く配る」だけでなく、<b style="color:#fff;font-weight:500">実際のAI利用</b>をオンチェインインセンティブの起点にします：\n      APIに使う資金が同時にFLOCK経済ループに参加します。'),
    ('<h3>对普通用户：调 API 就能进奖励池</h3>', '<h3>For everyday users: API calls enter the reward pool</h3>', '<h3>일반 사용자: API 호출만으로 보상 풀 참여</h3>', '<h3>一般ユーザー：API呼び出しで報酬プールへ</h3>'),
    ('如果你本来就要用 AI（写代码、跑 Agent、部署服务），在 FLock 上这笔花费<b style="color:#fff;font-weight:500">同时算进奖励</b>。', 'If you already use AI (coding, agents, deployed services), spend on FLock and it <b style="color:#fff;font-weight:500">counts toward rewards too</b>.', '원래 AI를 써야 한다면(코딩, Agent, 서비스 배포), FLock에서의 그 지출이 <b style="color:#fff;font-weight:500">보상에도 반영</b>됩니다.', 'もともとAIを使うなら（コーディング、Agent、サービス運用）、FLockでのその支出は<b style="color:#fff;font-weight:500">報酬にもカウント</b>されます。'),
    ('先产生真实调用，再质押你正在用的 MT 抬高权重，最后领取 FLOCK 和该模型的代币激励。', "Make real calls first, stake the MT you're using to lift weight, then claim FLOCK and that model's token incentives.", '먼저 실제 호출을 만들고, 사용 중인 MT를 스테이킹해 가중치를 올린 뒤, FLOCK과 해당 모델 토큰 인센티브를 수령하세요.', 'まず実際の呼び出しを作り、使用中のMTをステーキングして重みを上げ、最後にFLOCKとそのモデルトークンのインセンティブを受け取ります。'),
    ('<div class="rl-head">奖励飞轮 · 四步循环（悬停高亮）</div>', '<div class="rl-head">Reward flywheel · four-step loop (hover to highlight)</div>', '<div class="rl-head">보상 플라이휠 · 4단계 루프(호버 하이라이트)</div>', '<div class="rl-head">報酬フライホイール · 4ステップループ（ホバーでハイライト）</div>'),
    ('data-detail="在 API Platform 调用你需要的模型，产生真实 AI 花费。"', 'data-detail="Call the models you need on API Platform and generate real AI spend."', 'data-detail="API Platform에서 필요한 모델을 호출해 실제 AI 지출을 만듭니다."', 'data-detail="API Platformで必要なモデルを呼び出し、実際のAI支出を発生させます。"'),
    ('<b>① 用 API</b><span>真实 AI 调用</span>', '<b>① Use API</b><span>Real AI calls</span>', '<b>① API 사용</b><span>실제 AI 호출</span>', '<b>① API利用</b><span>実際のAI呼び出し</span>'),
    ('data-detail="你的花费计入对应 MT 池子，决定你在池中的基础份额。"', "data-detail=\"Your spend lands in that MT's pool and sets your base share.\"", 'data-detail="지출이 해당 MT 풀에 반영되어 풀 내 기본 몫을 결정합니다."', 'data-detail="支出が該当MTプールに計上され、プール内の基本シェアが決まります。"'),
    ('<b>② 产生花费</b><span>计入该 MT 池子</span>', '<b>② Generate spend</b><span>Counted in that MT pool</span>', '<b>② 지출 발생</b><span>해당 MT 풀에 반영</span>', '<b>② 支出発生</b><span>該当MTプールに計上</span>'),
    ('data-detail="质押你实际在用的 MT，获得额外权重，份额进一步提升。"', 'data-detail="Stake the MT you actually use for extra weight and a higher share."', 'data-detail="실제로 쓰는 MT를 스테이킹해 추가 가중치와 더 높은 몫을 얻습니다."', 'data-detail="実際に使うMTをステーキングし、追加の重みとより高いシェアを得ます。"'),
    ('<b>③ 质押 MT</b><span>抬高你的权重</span>', '<b>③ Stake MT</b><span>Lift your weight</span>', '<b>③ MT 스테이킹</b><span>가중치 상승</span>', '<b>③ MTステーキング</b><span>重みを引き上げ</span>'),
    ('data-detail="每日领取 FLOCK 与 Model Token 激励，循环继续。"', 'data-detail="Claim daily FLOCK and Model Token incentives; the loop continues."', 'data-detail="매일 FLOCK과 Model Token 인센티브를 수령하고 루프가 계속됩니다."', 'data-detail="毎日FLOCKとModel Tokenインセンティブを受け取り、ループが続きます。"'),
    ('<b>④ 领奖励</b><span>FLOCK + 模型币</span>', '<b>④ Claim rewards</b><span>FLOCK + model token</span>', '<b>④ 보상 수령</b><span>FLOCK + 모델 토큰</span>', '<b>④ 報酬受取</b><span>FLOCK + モデルトークン</span>'),
    ('<span class="rl-readout-text" id="rlReadoutText">在 API Platform 调用你需要的模型，产生真实 AI 花费。</span>', '<span class="rl-readout-text" id="rlReadoutText">Call the models you need on API Platform and generate real AI spend.</span>', '<span class="rl-readout-text" id="rlReadoutText">API Platform에서 필요한 모델을 호출해 실제 AI 지출을 만듭니다.</span>', '<span class="rl-readout-text" id="rlReadoutText">API Platformで必要なモデルを呼び出し、実際のAI支出を発生させます。</span>'),
    ('<p class="rl-hint">光点沿环路转动 · 悬停步骤查看说明</p>', '<p class="rl-hint">Dot travels the loop · hover a step for details</p>', '<p class="rl-hint">점이 루프를 따라 이동 · 단계에 호버하면 설명</p>', '<p class="rl-hint">点がループを回る · ステップにホバーで説明</p>'),
    ('<h3>对 FLOCK 持有者：核心激励资产</h3>', '<h3>For FLOCK holders: the core incentive asset</h3>', '<h3>FLOCK 보유자: 핵심 인센티브 자산</h3>', '<h3>FLOCK保有者：中核のインセンティブ資産</h3>'),
    ('FLOCK 正在变成整个 Model Token 体系里的<b style="color:#fff;font-weight:500">主奖励币</b>：每多一个模型、一批真实调用，都会把需求带回奖励循环。', 'FLOCK is becoming the <b style="color:#fff;font-weight:500">primary reward asset</b> across the Model Token stack: every new model and batch of real calls pulls demand back into the reward loop.', 'FLOCK은 Model Token 생태계 전반의 <b style="color:#fff;font-weight:500">주요 보상 자산</b>이 되고 있습니다: 모델과 실제 호출이 늘수록 수요가 보상 루프로 돌아옵니다.', 'FLOCKはModel Tokenエコシステム全体の<b style="color:#fff;font-weight:500">主報酬資産</b>になりつつあります：モデルと実呼び出しが増えるほど需要が報酬ループへ戻ります。'),
    ('gmFLOCK 持有者三大优势', 'Three gmFLOCK holder advantages', 'gmFLOCK 보유자 3대 장점', 'gmFLOCK保有者の3つの強み'),
    ('<div class="hb-title">全局加成</div>', '<div class="hb-title">Global boost</div>', '<div class="hb-title">글로벌 부스트</div>', '<div class="hb-title">グローバルブースト</div>'),
    ('<div class="hb-desc">一份 gmFLOCK，你参与的<b style="color:#fff">每个 MT</b> 都自动提升得分</div>', '<div class="hb-desc">One gmFLOCK automatically boosts your score on <b style="color:#fff">every MT</b> you join</div>', '<div class="hb-desc">gmFLOCK 하나로 참여하는 <b style="color:#fff">모든 MT</b> 점수가 자동 상승</div>', '<div class="hb-desc">gmFLOCK一枚で参加する<b style="color:#fff">すべてのMT</b>のスコアが自動向上</div>'),
    ('<div class="hb-title">复利效应</div>', '<div class="hb-title">Compounding effect</div>', '<div class="hb-title">복리 효과</div>', '<div class="hb-title">複利効果</div>'),
    ('<div class="hb-desc">模型越多，加成覆盖面越广 —— 相当于<b style="color:#fff">被动扩池</b></div>', '<div class="hb-desc">More models means wider coverage — like <b style="color:#fff">passive pool expansion</b></div>', '<div class="hb-desc">모델이 많을수록 부스트 범위 확대 — <b style="color:#fff">수동적 풀 확장</b>과 같음</div>', '<div class="hb-desc">モデルが増えるほどブースト範囲が拡大 — <b style="color:#fff">受動的なプール拡張</b>のようなもの</div>'),
    ('<div class="hb-title">小户友好</div>', '<div class="hb-title">Small-holder friendly</div>', '<div class="hb-title">소액 보유자 친화</div>', '<div class="hb-title">小口保有者に優しい</div>'),
    ('<div class="hb-desc">对数刻度设计，不需要巨鲸级别的持仓<b style="color:#fff">也能感受到差别</b></div>', '<div class="hb-desc">Log-scale design — no whale-sized bag needed to <b style="color:#fff">feel the difference</b></div>', '<div class="hb-desc">로그 스케일 설계 — 고래급 보유 없이도 <b style="color:#fff">차이를 느낄 수 있음</b></div>', '<div class="hb-desc">対数スケール設計 — クジラ級の保有量なしでも<b style="color:#fff">差を実感</b>できる</div>'),
    ('<p style="margin-bottom:6px;"><b>示意对比：</b>同样花 100 USDC 调 API</p>', '<p style="margin-bottom:6px;"><b>Illustrative comparison:</b> same 100 USDC on API calls</p>', '<p style="margin-bottom:6px;"><b>시뮬 비교:</b> 같은 100 USDC로 API 호출</p>', '<p style="margin-bottom:6px;"><b>デモ比較：</b>同じ100 USDCでAPI呼び出し</p>'),
    ('<span class="hc-label">不质押 · 无 gmFLOCK</span>', '<span class="hc-label">Not staked · no gmFLOCK</span>', '<span class="hc-label">미스테이킹 · gmFLOCK 없음</span>', '<span class="hc-label">未ステーキング · gmFLOCKなし</span>'),
    ('<span class="hc-label">质押 MT</span>', '<span class="hc-label">Staked MT</span>', '<span class="hc-label">MT 스테이킹</span>', '<span class="hc-label">MTステーキング</span>'),
    ('<span class="hc-label">质押 + gmFLOCK</span>', '<span class="hc-label">Staked + gmFLOCK</span>', '<span class="hc-label">스테이킹 + gmFLOCK</span>', '<span class="hc-label">ステーキング + gmFLOCK</span>'),
    ('这不是传统空投：奖励越来越看<b style="color:#fff;font-weight:500">真实 AI 需求</b>。用得早、用得真、持得久的人，长期更占优。', 'This isn\'t a classic airdrop: rewards increasingly track <b style="color:#fff;font-weight:500">real AI demand</b>. Use early, use for real, hold long — that wins over time.', '전통적인 에어드rop이 아닙니다: 보상은 점점 <b style="color:#fff;font-weight:500">실제 AI 수요</b>를 따릅니다. 일찍, 진짜로, 오래 쓰는 사람이 장기적으로 유리합니다.', '従来のエアドropではありません：報酬はますます<b style="color:#fff;font-weight:500">実際のAI需要</b>を反映します。早く、本当に、長く使う人が長期的に有利です。'),
    ('<div class="chip"><i data-lucide="terminal" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Spend</b> · 用 AI</div>', '<div class="chip"><i data-lucide="terminal" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Spend</b> · use AI</div>', '<div class="chip"><i data-lucide="terminal" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Spend</b> · AI 사용</div>', '<div class="chip"><i data-lucide="terminal" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Spend</b> · AIを使う</div>'),
    ('<div class="chip"><i data-lucide="anchor" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Stake</b> · 质押 MT</div>', '<div class="chip"><i data-lucide="anchor" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Stake</b> · stake MT</div>', '<div class="chip"><i data-lucide="anchor" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Stake</b> · MT 스테이킹</div>', '<div class="chip"><i data-lucide="anchor" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Stake</b> · MTをステーキング</div>'),
    ('<div class="chip"><i data-lucide="gem" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Hold</b> · 持有 gmFLOCK</div>', '<div class="chip"><i data-lucide="gem" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Hold</b> · hold gmFLOCK</div>', '<div class="chip"><i data-lucide="gem" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Hold</b> · gmFLOCK 보유</div>', '<div class="chip"><i data-lucide="gem" style="width:13px;height:13px;vertical-align:-2px;margin-right:6px;color:var(--blue);"></i><b>Hold</b> · gmFLOCK保有</div>'),
    ('<div class="chip" style="border-color:var(--border-blue);background:rgba(55,115,255,0.08);color:#fff;">低价囤币时代在结束 —— 接下来属于<b style="color:var(--blue);">真正在用 AI 的人</b>。</div>', '<div class="chip" style="border-color:var(--border-blue);background:rgba(55,115,255,0.08);color:#fff;">The cheap-accumulation era is ending — next up: <b style="color:var(--blue);">people actually using AI</b>.</div>', '<div class="chip" style="border-color:var(--border-blue);background:rgba(55,115,255,0.08);color:#fff;">저가 매집 시대는 끝나고 있습니다 — 이제는 <b style="color:var(--blue);">AI를 실제로 쓰는 사람</b>의 차례입니다.</div>', '<div class="chip" style="border-color:var(--border-blue);background:rgba(55,115,255,0.08);color:#fff;">底値で積む時代は終わりつつあります — 次は<b style="color:var(--blue);">AIを本当に使う人</b>の番です。</div>'),
    ('<h2>准备好参与 Season 1 了吗？</h2>', '<h2>Ready to join Season 1?</h2>', '<h2>Season 1 참여 준비되셨나요?</h2>', '<h2>Season 1に参加する準備はできましたか？</h2>'),
    ('<p>前往 FOMO 平台开始真实 API 调用，或返回新手手册了解完整发行流程。</p>', '<p>Go to the FOMO platform for real API calls, or back to the guide for the full launch flow.</p>', '<p>FOMO 플랫폼에서 실제 API 호출을 시작하거나, 가이드로 돌아가 전체 발행 흐름을 확인하세요.</p>', '<p>FOMOプラットフォームで実際のAPI呼び出しを始めるか、ガイドに戻って全体の発行フローを確認してください。</p>'),
    ('<a class="btn btn-primary" href="https://fomo.flock.io" target="_blank" rel="noopener">前往 FOMO 平台<i data-lucide="arrow-up-right"></i></a>', '<a class="btn btn-primary" href="https://fomo.flock.io" target="_blank" rel="noopener">Go to FOMO App<i data-lucide="arrow-up-right"></i></a>', '<a class="btn btn-primary" href="https://fomo.flock.io" target="_blank" rel="noopener">FOMO 앱으로 이동<i data-lucide="arrow-up-right"></i></a>', '<a class="btn btn-primary" href="https://fomo.flock.io" target="_blank" rel="noopener">FOMO アプリへ<i data-lucide="arrow-up-right"></i></a>'),
    ('<a class="btn btn-ghost" href="fomo-newbie-guide_May">返回新手手册</a>', '<a class="btn btn-ghost" href="fomo-newbie-guide_May-en.html">Back to guide</a>', '<a class="btn btn-ghost" href="fomo-newbie-guide_May-ko.html">가이드로 돌아가기</a>', '<a class="btn btn-ghost" href="fomo-newbie-guide_May-ja.html">ガイドへ戻る</a>'),
    ("content:'达标线'", "content:'Threshold'", "content:'기준선'", "content:'基準線'"),
    ("content:'展开'", "content:'Expand'", "content:'펼치기'", "content:'展開'"),
    ("#what details.eco-loop[open] summary::after{content:'收起';}", "#what details.eco-loop[open] summary::after{content:'Collapse';}", "#what details.eco-loop[open] summary::after{content:'접기';}", "#what details.eco-loop[open] summary::after{content:'折りたたむ';}"),
    ("if(v<=0) return '未持有';", "if(v<=0) return 'None';", "if(v<=0) return '미보유';", "if(v<=0) return '未保有';"),
    ("if(v<=25) return '少量持有';", "if(v<=25) return 'Light holdings';", "if(v<=25) return '소량 보유';", "if(v<=25) return '少量保有';"),
    ("if(v<=50) return '中等持有';", "if(v<=50) return 'Moderate holdings';", "if(v<=50) return '중간 보유';", "if(v<=50) return '中程度の保有';"),
    ("if(v<=75) return '较多持有';", "if(v<=75) return 'Heavy holdings';", "if(v<=75) return '많은 보유';", "if(v<=75) return '多めの保有';"),
    ("return '大量持有';", "return 'Very heavy holdings';", "return '대량 보유';", "return '大量保有';"),
    ("'基础份额 '+(base*100).toFixed(1)+'%（'+myV+'÷'+poolV+'）× 质押'+(stakeOn?'×1.5':'×1')+' × gmFLOCK×'+gmM.toFixed(2)+' ≈ '+pct.toFixed(1)+'%';", "'Base share '+(base*100).toFixed(1)+'% ('+myV+'÷'+poolV+') × stake '+(stakeOn?'×1.5':'×1')+' × gmFLOCK ×'+gmM.toFixed(2)+' ≈ '+pct.toFixed(1)+'%';", "'기본 몫 '+(base*100).toFixed(1)+'% ('+myV+'÷'+poolV+') × 스테이킹 '+(stakeOn?'×1.5':'×1')+' × gmFLOCK ×'+gmM.toFixed(2)+' ≈ '+pct.toFixed(1)+'%';", "'基本シェア '+(base*100).toFixed(1)+'% ('+myV+'÷'+poolV+') × ステーキング '+(stakeOn?'×1.5':'×1')+' × gmFLOCK ×'+gmM.toFixed(2)+' ≈ '+pct.toFixed(1)+'%';"),
    ("document.getElementById('avPhaseLabel').textContent=(t<0.2?'早期':t<0.7?'进行中':'后期')+' · 约 '+Math.round(t*100)+'%';", "document.getElementById('avPhaseLabel').textContent=(t<0.2?'Early':t<0.7?'Mid-season':'Late')+' · ~ '+Math.round(t*100)+'%';", "document.getElementById('avPhaseLabel').textContent=(t<0.2?'초반':t<0.7?'진행 중':'후반')+' · 약 '+Math.round(t*100)+'%';", "document.getElementById('avPhaseLabel').textContent=(t<0.2?'序盤':t<0.7?'進行中':'終盤')+' · 約 '+Math.round(t*100)+'%';"),
    ("document.getElementById('avGapText').innerHTML='当前阶段：质押比不质押大约多 <b style=\"color:#fff\">'+Math.round(gap*100)+'%</b> 得分（α≈'+alpha.toFixed(2)+'，仅作理解用）。';", "document.getElementById('avGapText').innerHTML='At this stage: staking earns about <b style=\"color:#fff\">'+Math.round(gap*100)+'%</b> more score than not staking (α≈'+alpha.toFixed(2)+', illustrative only).';", "document.getElementById('avGapText').innerHTML='현재 단계: 스테이킹이 미스테이킹보다 약 <b style=\"color:#fff\">'+Math.round(gap*100)+'%</b> 더 많은 점수(α≈'+alpha.toFixed(2)+', 이해용).';", "document.getElementById('avGapText').innerHTML='現段階：ステーキングは未ステーキングより約<b style=\"color:#fff\">'+Math.round(gap*100)+'%</b>多いスコア（α≈'+alpha.toFixed(2)+'、理解用）。';"),
]
# fmt: on

if __name__ == "__main__":
    root = Path(__file__).resolve().parent
    write_file(root / "s1_en.py", "en", [(e[0], e[1]) for e in ENTRIES])
    write_file(root / "s1_ko.py", "ko", [(e[0], e[2]) for e in ENTRIES])
    write_file(root / "s1_ja.py", "ja", [(e[0], e[3]) for e in ENTRIES])
